# Generated by Django 6.0.3 on 2026-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
