# Generated by Django 6.0.3 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dept_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
