# Generated by Django 6.0.3 on 2026-03-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_dept_id_employee_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='street',
        ),
    ]
